### ISSUE TITLE
Restart application with initialProps

### ISSUE THREAD

**Issue by oziks** [avishayil/react-native-restart#1]
I want to know if it would be possible to pass parameters to know the status of the application. Example, the number of times that the application has been restarted.

Exemple:

``` js
RNRestart.Restart({
  restartCause: 'Lorem ipsum',
});
```

That would be great, thanks :)

**Comment by avishayil** [comment]
Hi, I don't have the sufficient knowledge to implement something like this, any PRs would we welcomed :)

**Comment by avishayil** [comment]
@oziks I was wondering what would be the best way to implement something like this. Maybe using AsyncStorage?
Would love to get someone's help on this.

**Comment by avishayil** [comment]
I implemented something like this on the dev branch: https://github.com/avishayil/react-native-restart/tree/dev

You're welcome to try it if you like.

**Comment by leonardonelson91** [comment]
@avishayil and @oziks would you have an example on how to achieve this? I've tried to open the link you've last mentioned but I get a 404...
