### ISSUE TITLE
Error after update Android Repository

### ISSUE THREAD

**Issue by apuyapuy** [avishayil/react-native-restart#10]
Building and installing the app on the device (cd android && ./gradlew installDebug...
File /Users/dev/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-restart'.
      > Could not resolve all dependencies for configuration ':react-native-restart:_debugPublishCopy'.
         > Could not find com.atlassian.mobile.video:okhttp-ws-compat:3.7.0-atlassian1.
           Required by:
               AuditChamber:react-native-restart:unspecified > com.facebook.react:react-native:0.42.3-atlassian-1

Please help

**Comment by kristianm** [comment]
[This helped me](https://github.com/facebook/react-native/issues/14223#issuecomment-304447493)
