### ISSUE TITLE
null is not an object (evaluating 'x.default.restart;)

### ISSUE THREAD

**Issue by alirezadarvishi** [avishayil/react-native-restart#100]
I have an error when I use this library. How can I fix it?
 I use expo.
> null is not an object (evaluating 'x.default.restart;)

```
export default class App extends React.Component{
  constructor(props){
    if (I18nManager.isRTL) {
      RNRestart.Restart();
    }
    super(props);
    this.state={
      fontLoaded:false,
      loginstatus:null,
    }
  }
........
```

**Comment by avishayil** [comment]
If i'm not wrong, you have to eject your expo app in order to use this library.

**Comment by ManigandanRaamanathan** [comment]
@avishayil it returning the same error on pure react native that don't use expo

**Comment by raphaelpinel** [comment]
Why is this issue closed? 
I am not using expo, am using RN 0.63.3 and react-native-restart 0.0.20
I've got the same problem, on android only, when calling RNRestart.Restart() from an Alert button
`null is not an object (evaluating '_reactNativeRestart.default.Restart')`
```
Alert.alert(
          "Restart app?", 
          "You have changed the app language. You need to restart the app for it to be effective.", 
          [
            {
              text: "Do it later",
              style: "cancel"
            },
            {
              text: "Restart now",
              onPress: () => RNRestart.Restart()
            },
          ],
          { cancelable: false }
        );
```
![Screenshot 2021-01-04 at 12 00 53](https://user-images.githubusercontent.com/36964192/103523872-43cc2000-4e85-11eb-9c88-9f0cfea4dbcf.png)

**Comment by Degn** [comment]
Same issue for me and I'm not using Expo either.. Anyone with a solution yet? :)

**Comment by crutchcorn** [comment]
Can confirm that I'm experiencing this on Android as well. This issue should be re-opened. I'll be taking a look at the code to see if I can't just make a PR to fix this

**Comment by crutchcorn** [comment]
Update: manually linking the project seems to've fixed the issue for me. Might be some error in the auto-linking process. I would love to submit a PR, but have admittedly never run into auto-link documentation that I felt explained things properly and I've never had issues with my libraries auto-linking so I'm not even sure where to start debugging.

**Comment by yunusc5n** [comment]
Yes, the manual linking is working and its `react-native link react-native-restart`

**Comment by KrisLau** [comment]
Not working even with manual linking for me

**Comment by haifaash87** [comment]
I face the same issue even after manual linking. Kindly help

**Comment by RhysTowey** [comment]
This works fine in 'production' mode (tested with RN 0.67.2). In 'dev' mode, try using `DevSettings.reload()` from [https://reactnative.dev/docs/devsettings#reload](https://reactnative.dev/docs/devsettings#reload)

**Comment by ulfet-dev** [comment]
@RhysTowey but it takes too long time!!

**Comment by SinghRameshwar** [comment]
Same Issue here any one can help..?
