### ISSUE TITLE
Upload fix v0.60 

### ISSUE THREAD

**Issue by andreslargo** [avishayil/react-native-restart#102]
Please 

Update the release on npm packages.

Actually version 0.012 doesn't work in iOS.

For fix that problem I had to change ios/RCTRestart.podspec manually.

FIX: https://github.com/avishayil/react-native-restart/commit/55e2f85f094f56a3dedbe06b2610dd1b6aa34f63

**Comment by avishayil** [comment]
Released 0.0.13.
