### ISSUE TITLE
Question - Dangers?

### ISSUE THREAD

**Issue by cristianoccazinsp** [avishayil/react-native-restart#104]
Just wondering, what are the dangers of doing the full bundle restart? Have you found any caveat?
I need this to trigger a full UI restart due to some configuration changes that an only be re-applied on module import/load time. The library seems to work wonders, but I'm wondering the caveats... There's never free lunch!

**Comment by cristianoccazinsp** [comment]
Update:

On iOS, it seems like it leaks memory and after a couple of restarts the app's memory grows quite large. Is it possible to release the bundle before reloading it? Or after it.

**Comment by avishayil** [comment]
Hi, that is an interesting question as I never tested this in performance point of view. You're more than welcome to continue your investigation as we might find workarounds or solutions to these problems.

**Comment by cristianoccazinsp** [comment]
After some testing both iOS and Android seem to leak memory after each restart. I've reduced the leaks to a minimum by basically unmounting every component before restart happens (and basically leaving only a single root/dummy component). However, on iOS with an iphone 7, each restart would add about 10-15Mb of RAM that is never returned. About 30 restarts later, the app is killed due to oom.

I know this would be very rare, and most likely to RN internals itself since a restart like this is really never supposed to happen. But it would be good to at least have a warning about it.

**Comment by avishayil** [comment]
Seems like a plan. Can you create a notice in the Readme file?

**Comment by cristianoccazinsp** [comment]
Sure

**Comment by drinikol** [comment]
I have notice this, performance hit when a restart is done.  How did you do lessen the leak? @cristianoccazinsp

**Comment by cristianoccazinsp** [comment]
Did you actually notice the device running slower? I've only seen the
memleak.

Basically, I made sure everything is unmounted and that the components
themselves dont leak.

**Comment by yamov** [comment]
@cristianoccazinsp how did you measure the memory consumption?
I tried the debug build and used the RN's Perf Monitor and I couldn't notice any change in memory consumption after multiple restarts in our app. Right after the restart there is a spike in memory use but then when the app stays idle it gets back to the normal level.

**Comment by cristianoccazinsp** [comment]
On android, I used the dev tools to monitor the memory after each restart.
Not only that, also using a very cheap device eventually crashed due to OOM.


On iOS, I monitored the memory in the prod builds with the react native
device info library. That one can give you an estimate of the JS memory
being used. Also, an iPhone 7 would eventually crash due to OOM after many
(30 or 40) restarts.

**Comment by yamov** [comment]
Thanks. Will try measuring it in release builds as well.

**Comment by ajaykumar97** [comment]
Any update on this memory leak issue?
After 3-4 restarts, then my app becomes very laggy. Any solutions for this issue?
