### ISSUE TITLE
build error on  react-native "0.61.4"

### ISSUE THREAD

**Issue by mnajmi** [avishayil/react-native-restart#109]
When i add react-native-restart 
react-native run-android failed and show blow error
error Task :app:transformDexArchiveWithDexMergerForDebug FAILED

**Comment by masoudltf** [comment]
Same error!

**Comment by jay-thanki** [comment]
facing same error `Task :react-native-restart:compileDebugJavaWithJavac FAILED`

**Comment by SaeedZhiany** [comment]
@mnajmi 

if you used this library on RN version 0.59.10 or **below**, make sure to unlink this repository (and all the other Libs that support auto-linking).

I already test it on RN 0.61.5 and it working fine.
