### ISSUE TITLE
[android] Restart only restarts the virtual Dom, not the entire JS application

### ISSUE THREAD

**Issue by thomasttvo** [avishayil/react-native-restart#11]
Restart only restarts fully on iOS. On Android though, it only reloads the react native virtual dom tree. All the imported modules are left intact. This is critical as each time we restart on Android, the states might get more corrupted, and memory leak will be more severe.

**Comment by SoorajChandran** [comment]
Facing the same issue. Any work around for this? I need to completely restart the app as part of switching the layout ( LTR to RTL )

**Comment by yamov** [comment]
Heya.
Any updates on this issue? Or any workarounds?

**Comment by ashusdn** [comment]
I am also facing the same issue, it's only changed in DOM not affect on Styles if I manage something like below its not work in Android same code work properly in iOS 👍 
On Application, before restart, I am setting

 I18nManager.forceRTL(true);

Style Code : (not work in Android same code work properly in iOS)
 transform: [{ scaleX: I18nManager.isRTL ? -1 : 1 }]

Can anyone have any solution for this?

**Comment by Aleksandern** [comment]
I also have problem with Android (it works okay in iOS). I need to switch LTR to RTL and RTLE to LTR.
I've got error if I  tap screen after   RNRestart.Restart();
`Got DOWN touch before receiving UP or CANCEL from last gesture`

I use  [https://www.npmjs.com/package/react-native-restart-android](url)

**Comment by madsleejensen** [comment]
did a PR with a fix that worked for my case: https://github.com/avishayil/react-native-restart/pull/19

**Comment by avishayil** [comment]
Thanks @madsleejensen , merged.

**Comment by mannol** [comment]
Nah, doesn't work. If you have some global state it will remain intact by the restart.
