### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by bdebout** [avishayil/react-native-restart#13]
Hi, I made a stackoverflow post in order to solve an issue I have: https://stackoverflow.com/questions/44458716/react-native-restart-package-error

If you have an idea, I'll appreciate your help

**Comment by ozexpert** [comment]
same problem for me..

**Comment by ozexpert** [comment]
Oh.. you just need to rebuild. that's all. working for me.

**Comment by bdebout** [comment]
Can you post your gradle / MainApplication etc. ? like the same files I posted on stackoverflow.

**Comment by bdebout** [comment]
I can't even build the app right now. My problem comes from my MainApplication, I followed the Android Manual installation RN>=0.29
