### ISSUE TITLE
unable to find remote helper for 'git+https'

### ISSUE THREAD

**Issue by veeru03** [avishayil/react-native-restart#136]
!] Error installing RCTRestart
[!] /usr/bin/git clone git+https://github.com/avishayil/react-native-restart.git /var/folders/t_/mf1sbq153g5crs9fwc83l9lh0000gq/T/d20200711-5699-10ore3g --template= --single-branch --depth 1 --branch v0.0.13

Cloning into '/var/folders/t_/mf1sbq153g5crs9fwc83l9lh0000gq/T/d20200711-5699-10ore3g'...
fatal: unable to find remote helper for 'git+https'

**Comment by avishayil** [comment]
Hi @veeru03 could you please write step by step which commands did you type until you encountered this error?
Thanks.

**Comment by veeru03** [comment]
Hi @avishayil at the time of pod install in ios folder i getting this error
 "react-native-restart": "0.0.13",
    "react-native": "0.60.3",
steps which i followed are :- 
1. npm install react-native-restart 
2. cd ios
3. pod install 
and then i get this error

**Comment by avishayil** [comment]
Very weird as I can't seem to replicate this...
