### ISSUE TITLE
Failed to find target with hash string '28' in:  ....../sdk

### ISSUE THREAD

**Issue by silencer07** [avishayil/react-native-restart#138]
I am having that error in my project after installing this library.

Also tried installing Android SDK 28 (Android Pie) in SDK Manager in android studio but i have the same problem

- React Native 0.63.2
- Did not use npm link

**Comment by nenko** [comment]
Having the same issue, any suggestion for fix ?

**Comment by avishayil** [comment]
Hi @silencer07 @nenko 
Did you manage to solve the issue?
Any reproducible repo?
