### ISSUE TITLE
Can we add the tvOS support ?

### ISSUE THREAD

**Issue by mehthabux** [avishayil/react-native-restart#140]
I’m developing a tvOS  app,  so when i tired to install this library , im getting error 

`The platform of the target `TestApp-tvOS` (tvOS 12.0) is not compatible with `react-native-restart (0.0.17)`, which does not support `tvOS``.

Is it possible to add tvOS support?

**Comment by mehthabux** [comment]
I fixed it , i updated the react-native-restart.podspec file

`require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-restart"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => "9.0", :tvos => "11.0" }
  s.source       = { :git => "https://github.com/avishayil/react-native-restart.git", :tag => "#{s.version}" }

  s.source_files = "ios/**/*.{h,m}"

  s.dependency "React"
end
` 

I just added tvos in s.platforms

**Comment by mehthabux** [comment]
#141

**Comment by avishayil** [comment]
Thanks! merged
