### ISSUE TITLE
RN-Windows C++ Implementation?

### ISSUE THREAD

**Issue by creambyemute** [avishayil/react-native-restart#145]
Hey @avishayil , as you support windows as well, would you be interested in having/participating/ a port of the windows C# implementation to C++? Most RN-Windows supported libraries nowadays have an C++ implementation because:

- It's faster for the startup
- C++ RN-Windows Template (the default) may have problems with C# implementations at the moment

**Comment by avishayil** [comment]
Interesting question. The issue you referenced is great, I'll wait for inputs and documentation to take this further. Feel free to open a PR to implement that.

**Comment by creambyemute** [comment]
I might give it a try this weekend!

**Comment by burtonrodman** [comment]
@creambyemute i need a C++ implementation now (as our project is eschewing C#).  I am willing to do it, but wonder if you ever got anything started?

**Comment by creambyemute** [comment]
@burtonrodman Yeah I started something but in the end kinda gave up on it because we can't upgrade to 0.64 as we don't know which library is causing the white screen launch in release mode (debug mode works fine).

For 0.63 check CodePush, they do the same but had to copy some stuff.
For 0.64 it should be really simple now according to the discussion in: https://github.com/microsoft/react-native-windows/issues/7324 .

Cheers

**Comment by Omar-Belghaouti** [comment]
Is there any news about this?

**Comment by burtonrodman** [comment]
@Omar-Belghaouti it looks like the PR is waiting on my feedback.  i’ll try to look at that today.  in the mean time, feel free to reference my fork and let me know of any issues.

**Comment by Omar-Belghaouti** [comment]
@burtonrodman thanks for the reply, I'll try your fork and let you know if I faced any issue

**Comment by Omar-Belghaouti** [comment]
@burtonrodman I don't know why they didn't merge your PR yet, it works just fine

**Comment by avishayil** [comment]
Merged in #167
