### ISSUE TITLE
new release to fix XCode 12 and tvOS issues?

### ISSUE THREAD

**Issue by csantos1113** [avishayil/react-native-restart#148]
Hi @avishayil - sorry to bother. 
Could you pls be so kind and create a new release that includes https://github.com/avishayil/react-native-restart/pull/141 and https://github.com/avishayil/react-native-restart/pull/143

I'm actually needing those changes and I would rather have them part of your package, instead of forking it.

Thanks 🙏

**Comment by avishayil** [comment]
new release coming
