### ISSUE TITLE
package deprecated?

### ISSUE THREAD

**Issue by webraptor** [avishayil/react-native-restart#154]
Hey @avishayil, npm shows the packages as deprecated. Is that an error or?

<img width="1272" alt="Screenshot 2020-12-18 at 13 15 10" src="https://user-images.githubusercontent.com/864054/102608774-17996b00-4133-11eb-919f-89599c6157c9.png">

**Comment by avishayil** [comment]
Weird! It should deprecate only the latest version. I'll take care of it, thanks!

**Comment by avishayil** [comment]
fixed by #155
