### ISSUE TITLE
Can we hide the green loading at the top in the production apk?

### ISSUE THREAD

**Issue by callmemonky** [avishayil/react-native-restart#156]

**Comment by avishayil** [comment]
I don't think so, since it's react native behavior... If you have any ideas I'd love to hear

**Comment by vietpf** [comment]
its actually not shown in production apk already

**Comment by adriandiaz** [comment]
Related: while green loading header is not shown in production (ios or android), does anyone know if there's a way to hide the white flash? I'm already using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen) to handle an OS refresh, but still seeing a white flash when invoking RNRestart

**Comment by viet97** [comment]
> Related: while green loading header is not shown in production (ios or android), does anyone know if there's a way to hide the white flash? I'm already using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen) to handle an OS refresh, but still seeing a white flash when invoking RNRestart
> 
> Update for those interested in the same problem. You can change the root view color to match the background splash screen for a more seamless refresh: https://medium.com/@Krizzu/how-to-change-background-color-of-rootview-in-react-native-3279417c34bb

i think just change splash screen in native ios and it will be fine

**Comment by avishayil** [comment]
Closing since this is not an "issue" and out of the scope of this library.
