### ISSUE TITLE
White screen after RNRestart.Restart()

### ISSUE THREAD

**Issue by TamaraMalakhova** [avishayil/react-native-restart#158]
I have white screen after RNRestart.Restart(). How to solve this problem?

**Comment by markovdigital** [comment]
same issue

**Comment by avishayil** [comment]
Can you please try to clone the example project and try to see if the issue persists?

What version of RN and the package do you see the issue in?

**Comment by DimitrisTzimikas** [comment]
@TamaraMalakhova lets say you are using react-native-splash-screen, you can SplashScreen.show(); when you are executing the restart.

**Comment by Abdulmalick-Dimnang** [comment]
> @TamaraMalakhova lets say you are using react-native-splash-screen, you can SplashScreen.show(); when you are executing the restart.

but how about if you're passing a style on the native side? for example
`SplashScreen.show(this, R.style.SplashScreenDarkTheme, true);`

If the layout launch_screen.xml depends on an attr then the app will just crash since we can't pass the style into .show() on the js's side

**Comment by shay-e-ls** [comment]
Any updates?
