### ISSUE TITLE
App Crash on Restart

### ISSUE THREAD

**Issue by muhammadhassan149** [avishayil/react-native-restart#162]
App doesn't come back after restart in Production in both android and iOS.
When I restart the application to change the Layout the app crashing (closing)

**Comment by avishayil** [comment]
Do you have any logs? Is this related to #161 ?

**Comment by vikasverma92** [comment]
https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067

this worked for me

**Comment by avishayil** [comment]
Please update if the issue could be reproduced using the example app / specify conditions / stacktrace to follow.
Closing for now

**Comment by tkyr-nm** [comment]
The same for me, on Android

**Comment by saadi-ninjasCode** [comment]
I solved the issue by adding some delay in calling `Restart()` . 
Here is my code.
`  i18next.changeLanguage(isArabic ? 'en' : 'ar').then(() => {
      I18nManager.forceRTL(!isArabic);
      setTimeout(() => {
        RNRestart.Restart();
      }, 100);
    });`

Try with this one. @tkyr-nm , @nriccar

**Comment by vladyslavNiemtsev** [comment]
The solution above did not solve the problem, only this PR - https://github.com/avishayil/react-native-restart/pull/211 was able to help

**Comment by saadi-ninjasCode** [comment]
> The solution above did not solve the problem, only this PR - #211 was able to help

I try this, but this PR will add a black screen on restart.

**Comment by elabayoub** [comment]
You can either use this : https://github.com/avishayil/react-native-restart/pull/211/files (worked for me but still crashed on Android 11) and run npx patch-package react-native-restart

**OR** add below code (worked for me on Android 11 >) in restart fun():

> @ReactMethod
public void Restart() {
Intent intent = getReactApplicationContext().getBaseContext().getPackageManager().getLaunchIntentForPackage(getReactApplicationContext().getBaseContext().getPackageName() );
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
getReactApplicationContext().startActivity(intent);
android.os.Process.killProcess(android.os.Process.myPid());
System.exit(0);
}

and run npx patch-package react-native-restart
