### ISSUE TITLE
Restarting on Android seems to quit the app instead of restarting

### ISSUE THREAD

**Issue by guytepper** [avishayil/react-native-restart#164]
On android, on the first app launch, when I call `RNRestart.Restart()` to update the UI to RTL, the app seems to quit intead of restarting (I don't get any crash report like I usually do)

On the 2nd app launch, I avoid the `Restart()` call since the UI has been updated, so it opens and displays the UI just fine.

I've seen #161 and #162 and I'm not sure if they're related, since I don't get a crash report like they do and for me it occurred only on Android (#162 occurred on both platforms)

(RN 0.63.4, no expo, hemres is off)

**Comment by avishayil** [comment]
I saw you resolved the issue on your side via https://github.com/guytepper/better-rail/pull/33
