### ISSUE TITLE
Update jcenter to mavencentral

### ISSUE THREAD

**Issue by PhilipBrew** [avishayil/react-native-restart#173]
As part of the [JCenter sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), we need to update uses of jcenter() to mavenCentral() in the android build.gradle

**Comment by avishayil** [comment]
Hi, yes, we will need to handle it until February, I tried to naively update the gradle files but it seems like more than that.

**Comment by AdhamMahmoud98** [comment]
Any update on the topic ?

**Comment by avishayil** [comment]
Hope to work on it this weekend. Do you have any suggestions regarding the migration?

**Comment by cameron-quad** [comment]
#186  seems to be what needs to change

**Comment by avishayil** [comment]
> #186 seems to be what needs to change @avishayil

Thanks, I tried to compile it locally and encountered some errors, I'll try to do some work around this on the weekend.

**Comment by avishayil** [comment]
fixed with #187
