### ISSUE TITLE
Why does this library exist?

### ISSUE THREAD

**Issue by rubek-joshi** [avishayil/react-native-restart#178]
All this library does is it just exports a react-native module and rebrands it as if it's its own. Was this really necessary? Or am I missing something?

**Comment by QinkangLu** [comment]
I check the code. You are absolutely right I believe

**Comment by linh1987** [comment]
It exports the native part of this module itself (eg the RNRestart is the module exposed by this package, not builtin to React-native)

https://github.com/avishayil/react-native-restart/blob/master/src/index.tsx#L3

**Comment by ImperatorOfIntellectualism** [comment]
This module doesn't even work LOL. It says that it's undefined even though I did define it.

**Comment by vanenshi** [comment]
> This module doesn't even work LOL. It says that it's undefined even though I did define it.

this package has a 36,907 weekly download (right now), maybe looking at your own code before commenting nonsense in Github is a better approach?
