### ISSUE TITLE
Could not find a declaration file for module 'react-native-restart'

### ISSUE THREAD

**Issue by deepakjsr7979** [avishayil/react-native-restart#184]
HI, 

This repo don't have typescript ?

**Comment by angelos3lex** [comment]
This is already fixed in master by https://github.com/avishayil/react-native-restart/pull/160, just not released yet on npm

**Comment by bombillazo** [comment]
Hey, how does one fix this locally while the change is reflected in npm?

**Comment by avishayil** [comment]
Published v0.0.23 with this fix
