### ISSUE TITLE
White Screen still appearing after adding splash screen.

### ISSUE THREAD

**Issue by ahadtechcarrot** [avishayil/react-native-restart#194]
Hi,

I tried with Splashscreen.show() method wherever I use RNRestart.Restart() as it was mentioned in [#158 ](https://github.com/avishayil/react-native-restart/issues/158) but still the white screen is appearing both in Android and IOS. Can anyone suggest a better approach to remove the white screen?

**Comment by ahadtechcarrot** [comment]
@avishayil can you please provide any update regarding this issue?

**Comment by muazazhar** [comment]
This works for me..
`import SplashScreen from 'react-native-splash-screen';`

and then where restarting use splashscreen.show method

`RNRestart.Restart();
 SplashScreen.show();`

**Comment by saadi-ninjasCode** [comment]
> This works for me.. `import SplashScreen from 'react-native-splash-screen';`
> 
> and then where restarting use splashscreen.show method
> 
> `RNRestart.Restart(); SplashScreen.show();`

`react-native-splash-screen` is not maintained. While there is another up-to-date library [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash). But they remove the **show** function when updating the library for supporting RN 0.70+

Currently, there is no way to show a splash screen with [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash)  on Restart. If anyone finds out solution. Please let me know. I am suffering from this issue

Previously, I am using the same solution (Showing splash on restarting the app).

**Comment by Melekhin** [comment]
> > This works for me.. `import SplashScreen from 'react-native-splash-screen';`
> > and then where restarting use splashscreen.show method
> > `RNRestart.Restart(); SplashScreen.show();`
> 
> `react-native-splash-screen` is not maintained. While there is another up-to-date library [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash). But they remove the **show** function when updating the library for supporting RN 0.70+
> 
> Currently, there is no way to show a splash screen with [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) on Restart. If anyone finds out solution. Please let me know. I am suffering from this issue
> 
> Previously, I am using the same solution (Showing splash on restarting the app).

So at the moment is there an option to manually show splash screen after manually restarting the app?
