### ISSUE TITLE
Touchable views and inputs not working after restart

### ISSUE THREAD

**Issue by yamila-fraiman** [avishayil/react-native-restart#196]
After restarting the app, buttons and inputs are not working. It was an expo app and I run expo eject, I'm not sure if it's related, or maybe some other libs such us expo-splash-screen. Any idea?

Version 0.0.24

https://user-images.githubusercontent.com/284215/160178768-1d3a54b3-e00d-4726-a858-236bda0c4e1e.mp4

**Comment by TIGeMi** [comment]
Also facing this issue. Do you have any solutions? @yamila-fraiman

**Comment by TIGeMi** [comment]
> Also facing this issue. Do you have any solutions? @yamila-fraiman

I used react-native actionsheet to trigger some actions and then restart. But restart() was called before so I got this issue. Fix by waiting for actions done completely, then call restart()

**Comment by avishayil** [comment]
v0.0.25 is released and will handle such issues. Please report if the issue persists.
