### ISSUE TITLE
mock using jest

### ISSUE THREAD

**Issue by Shahanshah87** [avishayil/react-native-restart#214]
I want to mock this package, I am using jest for testing.
` TypeError: Cannot read properties of undefined (reading 'Restart')`

**Comment by mimitch2** [comment]
Same

**Comment by mimitch2** [comment]
Ahhh, figured it out for anyone who lands here. You need to add a mock, and point to it via jest.config.js or under jest in package.json:

1. Add a top level folder in your repo __mocks__
2. inside that, create a file called react-native-restart.js
3. Add this to the file:
`export default {
    Restart: jest.fn()
};`
4. In either jest.config.js or under "jest" in package.json, add this entry under `moduleNameMapper`:
`moduleNameMapper: 
     .....
     {'react-native-restart': '<rootDir>/__mocks__/react-native-restart.js'
}`

Now you can import and mock like so:

`import RNRestart from 'react-native-restart';
     .....
     it('should render restart button and call RNRestart', () => {
        jest.spyOn(RNRestart, 'Restart');

        const error = {
            name: '',
            message: 'Custom message'
        };

        const { getByText } = render(
            <VRError level="error" error={error} trackId="track_id" />
        );
        fireEvent.press(getByText('Restart'));

        expect(RNRestart.Restart).toHaveBeenCalledTimes(1);
    });

`

**Comment by avishayil** [comment]
Great resolution @mimitch2 ! Thanks
