### ISSUE TITLE
Android restarting doesn't affect forcing RTL

### ISSUE THREAD

**Issue by MorcosS** [avishayil/react-native-restart#22]
I am implementing a restart for the app to change the language and to switch the app view from Right to left or vice-versa. 
that is my code here.

```
 if(this.state.firstItem && strings.getLanguage() === 'ar') {
        I18nManager.forceRTL(false)
        strings.setLanguage('en')
        console.log('language','en')
        AsyncStorage.setItem('@language:key','en');
    }else if(this.state.firstItem === false && strings.getLanguage() === 'en'){
         I18nManager.forceRTL(true)
        strings.setLanguage('ar')
        console.log('language','ar')
        AsyncStorage.setItem('@language:key','ar');
    }
    else {
        this.setState({ modalVisible: false});
        return ;
    }
    this.forceUpdate()
    RNRestart.Restart()
       //   RestartAndroid.restart()
  }

```

After restarting the app is in the other language but the Layout is not correct , I have to close the app and reopen it for the forcing Layout to take place.

**Comment by avishayil** [comment]
I guess this is related to the fact that reloading the bundle doesn't completely emulates device language switch, which is the base for `I18nManager` support.
````
When working on a new feature, you can easily toggle this button and reload the app to see RTL layout. The benefit is you won't need to change the language setting to test, however some text alignment won't change, as explained in the next section. Therefore, it's always a good idea to test your app in the RTL language before launching.
````
https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html
The restart package emulates only bundle refresh, and not 'killing' the app. I guess it is up to fb to improve the forceRTL function to behave better with bundle refresh.
