### ISSUE TITLE
Cannot read property 'Restart' of undefined

### ISSUE THREAD

**Issue by hazardsy** [avishayil/react-native-restart#23]
Hi there !

I am having some issues with using react-native-restart. I run into a "Cannot read property 'Restart' of undefined" error message when trying to restart my app on Android. I am unable to try on iOS at the moment.

My code is the following : 

```
disconnect = () => {
    firebase.auth().signOut().then(() => RNRestart.Restart());
}
```

This function is called in an onPress event from a TouchableOpacity.
I checked in my MainActivity.Java file that the package was linked, and everything seems right (import and getPackages). 

Is there anything I could do to fix this ?

Thanks !

**Comment by blastering66** [comment]
Me too...

@avishayil  said it FIX 10 days ago... but its error this time...

please check this.

**Comment by davidhellsing** [comment]
Confirmed that IOS works but Android gives the error as described.


Using RN `0.50.4`

**Comment by LiShine** [comment]
me too
android
RN 0.51.0

**Comment by nicolascouvrat** [comment]
Could you give a minimum code to reproduce the issue? I've tried on Android as well (7.0), with a clean app created from `react-native init` and got no issue restarting the app as intended.

Are you using it in combination with other custom elements such as navigation, etc?

**Comment by LiShine** [comment]
Ok
I am now on react-native
It works - restarts
But await from asyncStorage is stuck ...

**Comment by LiShine** [comment]
OK
Now it restarts ok.
It was problem with something else - listening for appState events - causes on restart to hang up
Thanks

**Comment by avishayil** [comment]
Glad to see you worked it out! Please re-open if you encounter this again.

**Comment by chikarao** [comment]
So what was the solution to this issue? I see people saying it now restarts, but I'm getting the same error message when calling:

RNRestart.Restart();

**Comment by lishine** [comment]
For my case, as I wrote, when I removed these react-native listeners, the restart started working and working till this day, on android. Try removing things, starting from scratch...

**Comment by chikarao** [comment]
@lishine, I see. I'm using React-persist. I guess there is no way to make restart work while using persistStore and autoRehydrate?

**Comment by lishine** [comment]
Interesting, why you need restart?

**Comment by chikarao** [comment]
Well, I'm trying to refresh the app after logging out and deleting the auth token from asyncstorage. When I try to log in again, the app is not refreshed like I'm reloading/refreshing (like doing cmd R on the simulator). When I log back in, the app seems to be out of whack and the tab bar doesn't render right, for instance. Perhaps it has something with setting state that I don't understand.  If I can refresh without restarting, I'm open to that as well. But I need react-persist to keep some data persisted on asyncstorage

**Comment by lishine** [comment]
I understand. Me to, needed it when rtl worked only after restart. Sort of hack. But now i do rtl manually. I use mobx. And login/logout works almost fine.
Check if it is indeed because of the persist library, maybe it is something else

**Comment by AlessandroVol23** [comment]
Got still the same problem that I get the message: "Cannot read property 'Restart' of undefined"
I simply have the import and the function in a button to restart. 
Code is here: https://github.com/AlessandroVol23/Counter10000/blob/master/app/screens/ScreenEnterPlayerNames.js
I've added the imports to the index file as well without any success. 
![image](https://user-images.githubusercontent.com/19362086/37569529-f2f6ca76-2ae3-11e8-8fef-9ad12a475105.png)
