### ISSUE TITLE
Library projects cannot set applicationId. applicationId is set to 'com.reactnativerestart' in default config.

### ISSUE THREAD

**Issue by Sunshine168** [avishayil/react-native-restart#231]
com.android.builder.errors.EvalIssueException: Library projects cannot set applicationId. applicationId is set to 'com.reactnativerestart' in default config.

https://github.com/avishayil/react-native-restart/blob/master/android/build.gradle#L29

after remove this line then work

**Comment by a2f0** [comment]
I am receiving the same error.  It looks like it just surfaced in v0.0.26

**Comment by avishayil** [comment]
Thanks, indeed. I'm releasing a hotfix.

**Comment by avishayil** [comment]
Fixed in https://github.com/avishayil/react-native-restart/commit/c1552e35103e074fcb1eca0f8cc36a83825d4209
