### ISSUE TITLE
A function with a name starting with an uppercase letter should only be used as a constructor  @babel/new-cap

### ISSUE THREAD

**Issue by Romick2005** [avishayil/react-native-restart#232]
Please rename `RNRestart.Restart();` to `RNRestart.restart();` to make it correct due to conventions.

**Comment by avishayil** [comment]
Thanks, this will be supported already in the v0.0.27 hotfix.

**Comment by avishayil** [comment]
Fixed in https://github.com/avishayil/react-native-restart/commit/c1552e35103e074fcb1eca0f8cc36a83825d4209
