### ISSUE TITLE
FUCK ISRAEL! FREE PALESTINE!

### ISSUE THREAD

**Issue by bekroz** [avishayil/react-native-restart#259]
## Description

**Is this a bug report or a feature request?**

- [ ] Bug Report
- [ ] Feature Request

**Library Version**: 

**React Native Version**: 

**Platform(s)**:

- [ ] iOS
- [ ] Android

**Description**:

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

**Expected Behavior**:

**Actual Behavior**:

## Your Environment

**Operating System**: 

**Development Environment**: 

**Node.js Version**: 

**NPM/Yarn Version**:

**Comment by avishayil** [comment]
I hope you'll do something better with your life

**Comment by RMabroukS** [comment]
@bekroz  For this reason, I developed this package for restart app . https://www.npmjs.com/package/react-native-restart-app.  #FreePalestine
