### ISSUE TITLE
something went wrong while linking.

### ISSUE THREAD

**Issue by Mohammed-Saeed** [avishayil/react-native-restart#26]
rnpm-link info Linking react-native-restart ios dependency
rnpm-link ERR! It seems something went wrong while linking. 
Error: ENOENT: no such file or directory
,open 'C:\Users\MohamedSaeed\AwesomeProject\node_modules\react-native-restart\ios\RCTRestart.xcodeproj\project.pbxproj'

(node:3440) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: ENOENT: no such file or directory, open 'C:\Users\MohamedSae
ed\AwesomeProject\node_modules\react-native-restart\ios\RCTRestart.xcodeproj\pro
ject.pbxproj'
(node:3440) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by avishayil** [comment]
Try to manually link the library by dragging `RCTRestart.xcodeproj` to the `Libraries` section on Xcode than drag `RCTRestart.a` from `Products` folder to `Link binary with libraries` build phase.

Let me know if you have any other questions.
