### ISSUE TITLE
Are you using this open-source project to illustrate Hamas Israel?

### ISSUE THREAD

**Issue by ShaoGongBra** [avishayil/react-native-restart#265]
## Description

**Is this a bug report or a feature request?**

- [ ] Bug Report
- [ ] Feature Request

**Library Version**: 

**React Native Version**: 

**Platform(s)**:

- [ ] iOS
- [ ] Android

**Description**:

## Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

**Expected Behavior**:

**Actual Behavior**:

## Your Environment

**Operating System**: 

**Development Environment**: 

**Node.js Version**: 

**NPM/Yarn Version**:

**Comment by avishayil** [comment]
Hello @ShaoGongBra ,
That's my little piece on the web and I can definitely say that ones that support killing my people and my family are NOT welcome here.

**Comment by RMabroukS** [comment]
@ShaoGongBra  For this reason, I developed this package for restart app . https://www.npmjs.com/package/react-native-restart-app.  #FreePalestine
