### ISSUE TITLE
Request to Use Minor Version for Breaking Changes

### ISSUE THREAD

**Issue by phazei** [avishayil/react-native-restart#269]
I noticed that react-native-restart uses patch versions for all updates, including those with breaking changes. This makes dependency management tricky, especially given the various compatibility requirements with different React Native versions.

Could we switch to using the minor version for significant updates? It would help clarify what each update entails and manage dependencies more predictively.

thanks

**Comment by avishayil** [comment]
Sounds great, will be taken to account on next releases.
