### ISSUE TITLE
[Android] Restart() is Undefined

### ISSUE THREAD

**Issue by VectorIV** [avishayil/react-native-restart#3]
Hi,

I have been trying to get RNRestart.Restart(); to work for a while now. I have just recently noticed that the error stated that 'Restart is undefined.' The package seems to be imported just fine though (since it seems to recognise RNRestart), but somehow, I can't access Restart() nor getName().

I am new to React Native, and I properly have no idea what I am actually doing. I am using React Native version 0.37.0.

Thank you for your time.

**Comment by avishayil** [comment]
Do you still suffer form this? I can't tell why this can happen...

**Comment by avishayil** [comment]
@VectorIV Please let me know if you have any more problems...
Closing this for now.
