### ISSUE TITLE
Cannot read property Restart of undefined

### ISSUE THREAD

**Issue by psloboda** [avishayil/react-native-restart#31]
When I install the dependency react-native-restart, I did the automatic installation via react-native link with successfully linked result.

Environment: macOs and iOS emulator

![screen shot 2018-04-09 at 22 41 29](https://user-images.githubusercontent.com/14012806/38521869-30b14ed0-3c47-11e8-9c19-d3eae7cec00d.png)

My usage is
`import RNRestart from 'react-native-restart';`

and then in one action I call
`RNRestart.Restart();`

but got error - 'Cannot read property Restart of undefined'

![screen shot 2018-04-09 at 22 40 16](https://user-images.githubusercontent.com/14012806/38521934-5f0234a2-3c47-11e8-9b0f-2e47cf2a338b.png)

**Comment by blefebvre** [comment]
Hi @psloboda , I ran into the same issue. What worked for me was to open the Xcode project and manually perform the linking step. From the README:

> Ensure that libRCTRestart.a is linked through Link Binary With Libraries on Build Phases:

![image](https://user-images.githubusercontent.com/1048207/38928408-bbfa2f44-42d6-11e8-879f-1564cb4b7abb.png)

**Comment by RusselFourteen** [comment]
@blefebvre Hi sir, i already did the manual linking but still i got the same issue like above. Wondering whats the problem :(

**Comment by psloboda** [comment]
I was not able to solve it with running react-native run-ios but, when I start the application directly from Xcode, the issue did not occured

**Comment by RusselFourteen** [comment]
@psloboda how about undefined is not an object (evaluating '_reactNativeRestart2.default.Restart')? i got this error when i tried to click onPress={() => RNRestart.Restart()}

**Comment by AlessandroVol23** [comment]
For me the problem just occurred when I was in development mode. After starting it without dev mode it worked.

**Comment by shushuy** [comment]
Option 1) Try to install a lower version like:  
- npm install react-native-restart@0.0.5 --save 
(0.0.6 its the actual version)

Option 2) Sometimes when you do a "react-native link react-native-restart" it don't successfully do everything, in my case I added this 2 lines of code in (android/app/src/main/javacom/"yourProjectName"/MainApplication.java) :

import com.avishayil.rnrestart.ReactNativeRestartPackage;  // <--- ADD THIS LINE

public class MainApplication extends Application implements ReactApplication {

	private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
  		......
	    @Override
	    protected List<ReactPackage> getPackages() {
	        ...
	        return Arrays.<ReactPackage>asList(
	                new MainReactPackage(),
	                new ReactNativeRestartPackage() // <---- ADD THIS LINE
	        );
	    }
	};
	......
	@Override
	public ReactNativeHost getReactNativeHost() {
    	return mReactNativeHost;
	}
};

**Comment by avishayil** [comment]
Could you verify if it works now in 0.0.7?

**Comment by Walaa106** [comment]
@avishayil still it's not working in 0.0.7!

**Comment by ajeets1978** [comment]
any solution around this ?

**Comment by Normence** [comment]
I ran into the same issue when I first installed the package and linked it to react native. Then it was solved when I closed the project and reran the `react-native link`. My version of 'restart' is 0.0.7 and I was testing on a real device via XCode.

**Comment by abdullah-abunada** [comment]
this is like my case, it dose not work under development mode, but its work fine under production mode.
can you fix it please???

**Comment by hedza06** [comment]
Any solutions?

**Comment by manelsanz** [comment]
Didn't work for me too. Not in dev mode, nor in release mode...

**Comment by itayperry** [comment]
Did anyone manage to solve this?

**Comment by ivkovicboris** [comment]
Any news on this ?
I am using 0.0.20 and still getting _Cannot read property 'Restart' of null_
