### ISSUE TITLE
Restarting app on iOS doesn't display splash screen

### ISSUE THREAD

**Issue by KasparasGud** [avishayil/react-native-restart#32]
So I have a splash screen set up that is shown to the user upon starting the app. On android whenever the app is restarted the initial splash screen is shown. On iOS it only works when I actually start the app and not when calling RnRestart.Restart().
Is this expected behaviour on iOS or just an issue with my project?

Thank you for your time in advance

**Comment by avishayil** [comment]
This is an expected behavior, because it doesn't perform a "real" restart but just reloading the JS bundle.

**Comment by FantasyVII** [comment]
Is there anyway I can show a splash screen while the app is restarting? Because just having a white screen when restarting the app looks really bad

**Comment by heypran** [comment]
> Is there anyway I can show a splash screen while the app is restarting? Because just having a white screen when restarting the app looks really bad

Did you find any solution to this?

**Comment by saurabh874** [comment]
Hi I am also facing same issue anybody find solution for same?

**Comment by sanj-1234** [comment]
> This is expected behavior, because it doesn't perform a "real" restart but just reloading the JS bundle.
Shall we add some skeleton loader instead of showing a blank white screen?

**Comment by sanj-1234** [comment]
> This is an expected behavior, because it doesn't perform a "real" restart but just reloading the JS bundle.

Shall we show a skeleton loader instead of showing a blank white screen

**Comment by 0AlexZhong0** [comment]
> > This is expected behavior, because it doesn't perform a "real" restart but just reloading the JS bundle.
> 
> Shall we show a skeleton loader instead of showing a blank white screen?

This will be better UX for sure, 👍

**Comment by tonydatw** [comment]
Anyone still trying to find a fix to this?

**Comment by M0mentu** [comment]
I'am still trying to solve this issue, .show() doesn't work on IOS

**Comment by puckj** [comment]
> Is there anyway I can show a splash screen while the app is restarting? Because just having a white screen when restarting the app looks really bad

I'm using react-native-bootsplash and it happened to me too, Did you find a solution?

**Comment by faizanviwell** [comment]
Is it resolved?
