### ISSUE TITLE
No podspec found for `RCTRestart`

### ISSUE THREAD

**Issue by l1br3** [avishayil/react-native-restart#34]
A fresh install on Xcode 9.4 and Cocoapods 1.5.3 using react-native-restart 0.0.6.

My `ios/Podfile` is like this

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myApp
  pod 'Fabric'
  pod 'Firebase/Messaging'
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  
end
``` 

Then I get the following error on a `pod install` while being in `ios` directory.

```shell
Fetching podspec for `RCTRestart` from `../node_modules/react-native-restart/ios`
[!] No podspec found for `RCTRestart` in `../node_modules/react-native-restart/ios`
```

And of course I checked that the module is in `node_modules`

**Comment by hasanal1995** [comment]
you can copy ios folder from repository, it is worked with me lol

**Comment by avishayil** [comment]
It is now fixed in 0.0.7.

**Comment by nnals** [comment]
I just ran into this issue with a fresh install of react-native-restart 0.0.13 and react-native 0.60.4. Changing the relevant line in the Podfile from `pod 'RCTRestart', :path => '../node_modules/react-native-restart'` to `pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'` and running `pod install` in ios/ again solved it for me.

**Comment by markl-vesper** [comment]
Started getting this during pod install after a fairly hefty RN upgrade which included this library

eventually got it working by changing Podfile entry

pod 'RCTRestart', :path => '../node_modules/react-native-restart' -> pod 'react-native-restart', :path => '../node_modules/react-native-restart'

can only assume if some kind of issue due to file renaming at some point. Just had to get things matching up and problem went away
