### ISSUE TITLE
RCTFatalException: Exception '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array' was thrown

### ISSUE THREAD

**Issue by lfkwtz** [avishayil/react-native-restart#39]
Works fine in Android, but on iOS we're getting:

```
Application threw exception RCTFatalException: Exception '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array' was thrown while invoking Restart on target RNRestart with params (
    "<null>"
)
```

I installed originally with `react-native link`. Then I added pods.

Both times I had the same error. Is the `Importing The Library` step required for iOS?

**Comment by avishayil** [comment]
All you need to do is just `react-native-link` step, without installing any pods...
If you like in the latest release pods are supported.

**Comment by lfkwtz** [comment]
I did that. I first installed with react-native link and I got the error I posted. Then I added pods and got the same error.

**Comment by avishayil** [comment]
Hi @lfkwtz , could you try installing the Example project and see if you encounter the same issue? Just clone it, `yarn`, `react-native link react-native-restart` and run. Did you encounter the same error?
