### ISSUE TITLE
iOS Deployment Target update needed

### ISSUE THREAD

**Issue by RaphCayou** [avishayil/react-native-restart#44]
Would it be possible to update the iOS deployment target in ios/RCTRestart.xcodeproj/project.pbxproj from `IPHONEOS_DEPLOYMENT_TARGET = 7.0` to `IPHONEOS_DEPLOYMENT_TARGET = 8.0` as it is required for iOS 12 support.
Thank you

**Comment by avishayil** [comment]
Hey @RaphCayou could you create a PR?
Make sure it won't hurt backwards compatibility as well.

**Comment by avishayil** [comment]
@fixed on #45
