### ISSUE TITLE
RN 5.6.0

### ISSUE THREAD

**Issue by nzrubin** [avishayil/react-native-restart#48]
hi im on RN 5.6.0 it doesnt work
says undefined is not an object

**Comment by JetClosing-Devs** [comment]
Seeing this too on 5.7

**Comment by JetClosing-Devs** [comment]
Error: undefined is not a function (evaluating 'w.Restart()')

**Comment by nzrubin** [comment]
hi Man
same for me, 
Undefined is not an object (evaluating'_reactNativeRestart2.default.Restart')
im on 5.6.0

my code:

`import React, { Component } from 'react';
import { View, Text, TouchableOpacity } from 'react-native';
import RNRestart from 'react-native-restart';

export default class Restart extends Component {
  _pushButton() {
    RNRestart.Restart();
  }
  render() {
    return (
      <View style={{ flex: 1, width: '100%' }}>
          <View style={Styles.titleHolder}><Text style={Styles.titleText}>Clean Up</Text></View>
          <TouchableOpacity
          onPress={() => this._pushButton()}
          style={styles.start}
          ><Text>Restart</Text>
          </TouchableOpacity>
      </View>
    );
  }
}`

**Comment by avishayil** [comment]
Hi, Please use the official example for reference on how to run this library.
