### ISSUE TITLE
Restart causes crashes on Android with error stack size 1038KB

### ISSUE THREAD

**Issue by namthnus** [avishayil/react-native-restart#49]
`RNRestart.Restart()` works fine on IOS. But it crashes on Android.

![screenshot_1540542312](https://user-images.githubusercontent.com/30401245/47554938-cf0c0b80-d934-11e8-916b-763939d01c70.png)

Checking the log show error bellow

> Exception in native call
> java.lang.RuntimeException: Could not invoke RNRestart.Restart
> at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
> at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
> at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
> at android.os.Looper.loop(Looper.java:154)
> at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
> at java.lang.Thread.run(Thread.java:761)
>                                                                         Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Method.invoke(Native Method)
> at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
> at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
> at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
> at android.os.Handler.handleCallback(Handler.java:751) 
> at android.os.Handler.dispatchMessage(Handler.java:95) 
> at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
> at android.os.Looper.loop(Looper.java:154) 
> at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
> at java.lang.Thread.run(Thread.java:761) 
>                                                                         Caused by: java.lang.StackOverflowError: stack size 1038KB
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)
> at com.testapp.MainApplication$1.getPackages(MainApplication.java:34)

Seems like the error `stack size 1038KB` is caused by a loop.

My versions: 
react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by omarkhaled11** [comment]
Same problem here, works fine on iOS but doesn't work on Android, and I also remember having similar issues with Android with this package about a year or so ago. I thought they would be fixed by now =/

**Comment by namthnus** [comment]
I end up using [react-native-restart-android](https://github.com/lequanghuylc/react-native-restart-android) for android. Even though it's not restarting as fast as this one on iOS.

**Comment by avishayil** [comment]
I never encountered this. Do you guys know what is he doing differently?
