### ISSUE TITLE
[Android] Restart() is Undefined

### ISSUE THREAD

**Issue by KBepo** [avishayil/react-native-restart#5]
Same as the guy before. Restart function is not defined on react-native 0.36 for android. RNRestart is recognised but the Restart() function is not.

What info can I tell you to help you?

**Comment by avishayil** [comment]
Hi @KBepo, can you provide a repo with the issue reproduced?

**Comment by davingreen** [comment]
Having this same issue on 0.36. Only difference I could find per instructions and example is that in Header Search Paths, '../node_modules/react-native-restart" was not recursive, but this did not solve the undefined error.

**Comment by avishayil** [comment]
Can you provide a repo with the issue reproduced, or provide reproducible steps?

**Comment by davingreen** [comment]
```
npm i --save react-native-restart@0.0.1
react-native link react-native-restart
```
This is being called in an onPress. 
```
            alert("App reset.")
            RNRestart.Restart()
```
That's the only steps I've taken...

**Comment by MaxToyberman** [comment]
I had the same problem, please check if you have imported 
`import com.avishayil.rnrestart.ReactNativeRestartPackage;  // <--- Import`
in MainApplication.java.
and add 
`new ReactNativeRestartPackage() // Add this line`
to : getPackages

**Comment by ozexpert** [comment]
Hi, @MaxToyberman I do have that under MainApplication.java but getting the same error.

**Comment by kitsune7** [comment]
I'm getting the same error even on iOS. It recognizes the library `react-native-restart`, but it doesn't recognize any default export.

**Comment by leanminmachine** [comment]
Same for me here, testing on iOS. Are there any alternatives?

**Comment by ranahyder87** [comment]
Anyone got solution?
<addr>undefined is not an object (evaluating '_reactNativeRestart2.default.Restart')</addr>

**Comment by fukuball** [comment]
Got "Cannot read property 'Restart' of undefined" on iOS, any update?

**Comment by avishayil** [comment]
Should be fixed with https://github.com/avishayil/react-native-restart/commit/682c6d352959bb26735f415f9685274740ad351c and https://github.com/avishayil/react-native-restart/commit/068eb81ed6dd5f6cb38c9e370140c15f7a18c9af

**Comment by RusselFourteen** [comment]
@ranahyder87  did you fixed undefined is not an object (evaluating '_reactNativeRestart2.default.Restart')?

**Comment by clevertree** [comment]
@RusselFourteen try restarting the bundler, or hell restart! That solved it for me

**Comment by Walaa106** [comment]
> @ranahyder87 did you fixed undefined is not an object (evaluating '_reactNativeRestart2.default.Restart')?

Did you solve it?

**Comment by ajeets1978** [comment]
object (evaluating '_reactNativeRestart2.default.Restart')?

Do we have any solution for this ?

**Comment by waseeld** [comment]
[TypeError: null is not an object (evaluating '_reactNativeRestart.default.Restart')]

Do we have any solution for this ?

**Comment by huseyintamer** [comment]
[TypeError: null is not an object (evaluating '_reactNativeRestart.default.Restart')]

Do we have any solution for this ?

**Comment by Vivers0** [comment]
This helped me - **android/app/build.gradle**
`...
dependencies {
    ...
    implementation project(':react-native-restart')
}`
