### ISSUE TITLE
No view to update.

### ISSUE THREAD

**Issue by Ali-Ayyad** [avishayil/react-native-restart#6]
I am getting this when using `RNRestart.Restart()`
![simulator screen shot feb 16 2017 12 50 02 pm](https://cloud.githubusercontent.com/assets/7542151/23018404/80e0afa8-f446-11e6-9d14-2c7b5d14bf00.png)

- react-native-restart version 0.0.2
- react-native version 0.40.0

Worked perfectly on react-native version 0.37.0

**Comment by Ali-Ayyad** [comment]
The error was from something else not related to the library. Thanks

**Comment by chrissm79** [comment]
Getting the same error w/ the same versions of `react-native-restart` & `react-native` 0.41.2

**Comment by Ali-Ayyad** [comment]
With new update this is no longer an issue.

**Comment by system65** [comment]
Getting the same error : 

- react-native-restart : 0.0.2

- react-native : 0.41.2

**Comment by Ali-Ayyad** [comment]
@system65  try upgrading react-native as well.

**Comment by system65** [comment]
Solved with upgrading react-native to : 0.44.0
