### ISSUE TITLE
144 MB size!!

### ISSUE THREAD

**Issue by msajadi832** [avishayil/react-native-restart#61]
Please remove build folder from ios example!
in this path:
node_modules/react-native-restart/Example/ios/build 
Its size is 300 Mb!

**Comment by avishayil** [comment]
Hi @msajadi832 , I'll publish a new version with this.

**Comment by avishayil** [comment]
Fixed with https://github.com/avishayil/react-native-restart/commit/92d3c33f9903b1d4237349c066906972fb164e23
