### ISSUE TITLE
Build with RN 0.58.3 and android SDK 28 fails

### ISSUE THREAD

**Issue by allan-cornet-eove** [avishayil/react-native-restart#62]
build release fails with RN 0.58.3 on android

ask :react-native-restart:verifyReleaseResources FAILED
Due to old compileSdkVersion and buildToolsVersion versions

fix:
replaces react-native-restart/android/build.gradle by attached file
[build.gradle.zip](https://github.com/avishayil/react-native-restart/files/2816856/build.gradle.zip)

Standard way is to use rootProject.ext.compileSdkVersion and rootProject.ext.buildToolsVersion

**Comment by allan-cornet-eove** [comment]
Please merge this commit and update package
https://github.com/labibramadhan/react-native-restart/commit/0412613789b325a950c4e104e4673c5f20636616

**Comment by SaeedZhiany** [comment]
@allan-cornet-eove 
the more reliable way to do that is fallback to default version if root project does not define a property. I can not modify your merge request, so I suggest to modify your merge request to something like below:

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
.
.
.
compileSdkVersion safeExtGet('compileSdkVersion', 28)
buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
.
.
.
minSdkVersion safeExtGet('minSdkVersion', 16)
targetSdkVersion safeExtGet('targetSdkVersion', 28)
```

**Comment by allan-cornet-eove** [comment]
> @allan-cornet-eove
> the more reliable way to do that is fallback to default version if root project does not define a property. I can not modify your merge request, so I suggest to modify your merge request to something like below:
> 
> ```
> def safeExtGet(prop, fallback) {
>     rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
> }
> .
> .
> .
> compileSdkVersion safeExtGet('compileSdkVersion', 28)
> buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
> .
> .
> .
> minSdkVersion safeExtGet('minSdkVersion', 16)
> targetSdkVersion safeExtGet('targetSdkVersion', 28)
> ```

code updated

**Comment by allan-cornet-eove** [comment]
Please do an npm package :)
