### ISSUE TITLE
Cannot read property Restart of undefined

### ISSUE THREAD

**Issue by vujevits** [avishayil/react-native-restart#65]
I installed the latest version with npm, then linked it, running it resulted in: Cannot read property Restart of undefined. When I checked the header search path in XCode, it was set to non-recursive. Changing it to recursive fixed the issue.

macOS: 10.14
XCode: 10.1
react-native: 0.57.7

**Comment by isaaclem** [comment]
There are 3 paths in total

`$(inherited)`
`/Applications/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include`
`$(SRCROOT/../../react-native/React)`

May I know exactly which one should be set to recursive?

**Comment by vujevits** [comment]
@isaaclem the readme mentions it the `Manual iOS Installation`: 
"Ensure that Header Search Paths on Build Settings has the path $(SRCROOT)/../node_modules/react-native-restart set to recursive"
For some reason it does not happen during automatic installation.

**Comment by calz10** [comment]
This package brought a headache! I've fixed the undefined issue in IOS like 'Cannot read property Restart of undefined' by unlinking r-n-restart package, removing node_modules and installing again and pod deintegrate, pod clean, and btw I have used the pod Installation it works for me. in the Read.me section it says no more configuration so remove anything connected to react-native-restart that was manually configured the thing in header search path! :). if you've got issue in android side because of unlinking in ios you might do installation manually in android.

**Comment by avishayil** [comment]
Thanks @calz10, I'd be happy if any of you can set up a PR with FAQ how to handle those issues, or even fix them.

**Comment by avishayil** [comment]
I'm just reminding here that special setups should be tested accordingly.
Any issue should be happening on the official example as well, so we'll be able to debug it.

**Comment by manelsanz** [comment]
I have the same problem, but in Android. I reinstalled, re linked, uninstalled and reinstalled the app on device, tested with dev and release build apk, and nothing works. Always says `Cannot read property Restart of undefined`.

**Comment by calz10** [comment]
@manelsanz  try
```
del %appdata%\Temp\react-native-* & cd android & gradlew clean & cd .. & del node_modules/ & npm cache clean --force & npm install & npm start -- --reset-cache
```
then repeat the process in the docs it should work properly in android side by linking or via manual integration :)

**Comment by avishayil** [comment]
I don't understand what's wrong with the automatic integration, i'll try to test it and report.

**Comment by manelsanz** [comment]
Sorry, I'm so sorry. Was my bad. I hadn't completed the install guide... When on readme says **RN < 0.29**, I thought the next step were only for that version. I hadn't scrolled down. I wasn't set the MainApplication config...
Now works nice. 
Thanks all!

**Comment by avishayil** [comment]
I believe that can be closed for now
