### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by aroberts91** [avishayil/react-native-restart#67]
When trying to run gradleAssemble on a build i receive the following:

` Execution failed for task ':react-native-restart:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/mcadmin/Desktop/MCGit/shopper/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/mcadmin/Desktop/MCGit/shopper/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/mcadmin/Desktop/MCGit/shopper/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values/values.xml:2749: error: resource android:attr/fontVariationSettings not found.
  /Users/mcadmin/Desktop/MCGit/shopper/node_modules/react-native-restart/android/build/intermediates/res/merged/release/values/values.xml:2750: error: resource android:attr/ttcIndex not found.
  error: failed linking references. `

I've read elsewhere that opening react-native-restart > android > build.gradle and changing:

compileSdkVersion 27
buildToolsVersion "27.0.3"

but this has not resolved the issue

**Comment by BeshoyEkram** [comment]
I faced the same issue too

**Comment by Tantuss** [comment]
If you use Android Gradle Plugin 3.3.0 you get this:

WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.0.
Android SDK Build Tools 28.0.3 will be used.


So it's not possible to compile with an older version

**Comment by Tantuss** [comment]
The following solved it for me.
Edit this file:
node_modules/react-native-restart/android/build.gradle

Change all the 26 versions to 28.

>    compileSdkVersion 28
>    buildToolsVersion "28.0.3"
>
>    defaultConfig {
>        minSdkVersion 16
>        targetSdkVersion 28
>        versionCode 1
>        versionName "1.0"
>    }
>

**Comment by BeshoyEkram** [comment]
thanks Tantuss for your reply .. now i can build the app but when the app restarted it crashed and never work again

**Comment by ianmcgregor** [comment]
Looks like this was fixed in v0.0.10 but hasn't been published to npm yet.

**Comment by BeshoyEkram** [comment]
when the app restarted it crashed and never work again , the error in log '  viewroot mpi senduseractionevent() mView ==null'

**Comment by DiegoBittencourtOfficial** [comment]
When you guys are going to publish this to npm?

**Comment by affanhashone** [comment]
I am also facing similar issue. can the team push the latest version

**Comment by lfkwtz** [comment]
@avishayil can we get 0.10 published?

**Comment by avishayil** [comment]
Sure.

**Comment by MaxInMoon** [comment]
@avishayil do you plan to do it soon or later? Thanks

**Comment by avishayil** [comment]
Released.
