### ISSUE TITLE
Redirect to specific screen after reset

### ISSUE THREAD

**Issue by rafaelfndev** [avishayil/react-native-restart#68]
Is possible reset and redirect to especific screen using [react-navigation](https://reactnavigation.org/docs/en/stack-navigator.html)? If not, is possible add this feature?

Example:

```
RNRestart.Restart({
    screen: Favorites,
    restartParam: {
        param1: 'some param',
        param2: 'some param2'
    }
});
```

So, take this param on screen with `this.props.navigation.getParam('restartParam');` or something like this...

Thanks.

**Comment by avishayil** [comment]
Hi, you're talking about a specific integration, which is out of scope.
If you can contribute this feature via PR, i'll consider adding it.
Thanks!

**Comment by rafaelfndev** [comment]
And without integration with any third library, just using only RNRestart?

```
RNRestart.Restart({
    obj: param,
    obj2: param2
});
```

And so, check this on start application:

```
componentDidMount() {
    RNRestart.getRestartParam(obj => {
        console.log(obj); // null or obj...
    });
}
```

So we were able to make decisions at the starting of the application based on the parameters passed on RNRestart.Restart()

This is would be a great feature, I would love to collaborate, but I have no idea how to develop it :(

**Comment by avishayil** [comment]
I believe that could be done by storing parameters on `AsyncStorage`, but I won't have the time to develop & test it properly. Maybe you can try to do it after I gave you the general direction.
