### ISSUE TITLE
[Error] RNRestart. was called with 1 arguments but expects 0 arguments

### ISSUE THREAD

**Issue by IljaDaderko** [avishayil/react-native-restart#7]
Hey, found this repo today and it has proven to be great way to return from major unknown issues.
I am using RNRestart alongside react-native alert, i.e. error occurs and I show alert like this:

```
   Alert.alert(
      'Somethign went wrong',
      'It is taking more than usual to log in, try restarting the app',
      [{ text: 'Restar', onPress: () => RNRestart.Restart() }],
      { cancelable: false }
    );
```
---
This works fine 👍 so I tried to clean up the code and refactor onPress to 
```
onPress: RNRestart.Restart
```
---
After making this change I am now getting error below:

> RNRestart. was called with 1 arguments but expects 0 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

This is not to big of a deal, but I'm curious to why it is not working? + this could confuse someone into thinking that library is not functioning properly.

**Comment by ms88privat** [comment]
The error message describes what happened. The onPress function will get called with the button index (or something like that). So it will get passed into the RNRestart function. But it expects none, because it doesn't need it

**Comment by BillyWM** [comment]
Event handlers receive an event object as an argument when they're invoked. You set RNRestart.Restart as an event handler. Therefore, you invoked it with 1 argument, but it expected 0.

The difference with the example you quoted from the docs is this:
`      [{ text: 'Restar', onPress: () => RNRestart.Restart() }],`

It's wrapped in an arrow function, so Restart isn't set as the handler, the outer arrow function is. The arrow function receives the implicit argument, and throws it away.

You'd want to do the same

` onPress: () => RNRestart.Restart()`

not

`onPress: RNRestart.Restart`
