### ISSUE TITLE
[Question] Headless / stuff running in background

### ISSUE THREAD

**Issue by cristianocca** [avishayil/react-native-restart#77]
I'm wondering what happens to any "background" code, or timers, or android's headless execution when the restart signal is sent? Does everything stop abruptly?

I guess I should try it myself first, but I just wanted to know if you have considered this or not. 

For example, I have an app that is currently running a foreground service (Java/Android) and at the same time runs "in background" tasks spawned from this service, and called through HeadlessJS. There are also background fetch events happening from time to time, that might run while the app is active. Lastly, there are some setInterval calls that might run periodically while the app is active.

What about any in flight network request? Do they die as well?

Thanks!

**Comment by cjroth** [comment]
I just tried this with https://github.com/joltup/react-native-threads and it correctly restarts both the main and child threads.

**Comment by avishayil** [comment]
Thanks @cjroth .
@cristianocca I never tested this scenario. If you have any conclusions, we'll be happy if you could share it here during your benchmarks.
