### ISSUE TITLE
Not dismissing opened Alert boxes

### ISSUE THREAD

**Issue by e55o** [avishayil/react-native-restart#85]
This package does not dismiss opened alert boxes, it just keeps them on top.

React-native versions tested on:
```
0.58.6
0.59.3
0.59.8
```
Do you have any solution for that?

**Comment by avishayil** [comment]
Hi, do you know if this also happens on the example project? Any repo or steps to reproduce?
I think that it's up to you to manage the application or components state. This library just reloads the JS bundle.

**Comment by AndryDev** [comment]
As a walkaround you can use setTimeout to wait for the modal to be dismissed, that's how I solved it.

**Comment by e55o** [comment]
This issue is only for Android as on iOS by default all alerts are dismissed.
To reproduce it, just create any sample project and anywhere in the code generate an `Alert.alert()`, after that set a timeout for 2 seconds, then run `RNRestart()`, you will notice that the alert will still be there, even after the bundle restarts

**Comment by e55o** [comment]
@AndryDev in my case the user might not dismiss the modal, i don't want it there after the restart

**Comment by avishayil** [comment]
I understand, I believe this is something out of scope. If you have any idea how to solve this, please feel free to contribute a PR...
