### ISSUE TITLE
Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by jdnichollsc** [avishayil/react-native-restart#86]
Hi mate, I'm getting this issue with RN 0.60

This is the link of the repo: https://github.com/jdnichollsc/randomuser-me

<img width="587" alt="Captura de Pantalla 2019-07-04 a la(s) 1 46 32 p  m" src="https://user-images.githubusercontent.com/2154886/60684259-35511280-9e62-11e9-9436-91f31135094d.png">

**Comment by avishayil** [comment]
Hi, RN60 is untested yet.
Ill find some time to test it and see if there are any gaps on integration.

**Comment by jdnichollsc** [comment]
Thanks mate, I understand, I need to migrate my plugins too 🙈

**Comment by jdnichollsc** [comment]
@avishayil I'm getting this same issue with the last version of RN :)
