### ISSUE TITLE
Restart doesn't make redux state reset ?

### ISSUE THREAD

**Issue by ptgamr** [avishayil/react-native-restart#9]
It seems after restart, the redux store is not reset to the initial state. I thought when reloading the whole bundle, the state should also be reset  ?

When I had the error set to true in the state like bellow, an error screen is displayed with a REFRESH button, in which it call `RNRestart.Restart`:

```
state = {
  error: true
}
```

But after the restart, error is still true --- my error screen still appear :(

**Comment by ptgamr** [comment]
It's only happened on Android... iOS is working just fine!

**Comment by a-koka** [comment]
This was happening for me too. Updating `redux`, `react-redux` and `react-native-restart` to latest seems to have fixed this issue. We can close this item.
