### ISSUE TITLE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.

### ISSUE THREAD

**Issue by anduscheung** [avishayil/react-native-restart#94]
I am getting this warning while trying to build an Android signed apk

'Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.'
<img width="1033" alt="Screenshot 2019-07-07 at 2 21 17 AM" src="https://user-images.githubusercontent.com/16278037/60759868-7746a800-a05e-11e9-82b0-25beddd556b2.png">

While the apk isn't seem able to be built with this warning existing. Any update to this?

My Gradle dependency is "com.android.tools.build:gradle:3.4.0 and I only installed this library in my project.

**Comment by anduscheung** [comment]
I'm using Android Gradle Plugin V3.4.1 and Gradle Version V5.4.1

**Comment by guaneagler** [comment]
Hi, man. How did you fix it? I have the same problem.
