### ISSUE TITLE
RN 0.60 Cannot read property "Restart" of undefined

### ISSUE THREAD

**Issue by Auticcat** [avishayil/react-native-restart#95]
Hello!

I'm having this error when i'm trying to implement this library in my app.

Things i've tried:
1)
`react-native link react-native-restart`
2)
`react-native link react-native-restart`
`cd ios`
`pod install`
3) 
pasting   pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios' in my podfile
`cd ios`
`pod install`
4)
reinstalling from 0
5)
Checked all other issues with same title

In all the cases the app build successfully and runs. The moment i try to use the library i get
`Cannot read property "Restart" of undefined`
Looking at issue [#86 ](https://github.com/avishayil/react-native-restart/issues/86) I see that react-native **0.60** has yet to be tested.

Are there any news about a future release for the support?

Thank you in advance for the patience

**Comment by avishayil** [comment]
Hi,
This library still doesn't support RN 0.60.
We need to find time to test the compatibility.

**Comment by Psiiirus** [comment]
@avishayil  just did a PR #96 
works fine on my app

**Comment by Auticcat** [comment]
Tested @Psiiirus solution and can confirm that it works both on debug that in production mode in my app!

**Comment by avishayil** [comment]
Glad!

**Comment by jake41** [comment]
@avishayil  please do a new build for this. Only after this RN 0.58 will also work via cocoapods installation

**Comment by novonimo** [comment]
It's work fine on RN 0.63.3

don't forget to rebuild your app after installing  'react-native-restart'  vie `npx react-native start --reset-cache`  or other alternative method.
