### ISSUE TITLE
React-native >0.60 support?

### ISSUE THREAD

**Issue by meabed** [avishayil/react-native-restart#98]
I have tried multiple ways to integrate the library in react-native 0.60.4 but i always end up with an error like 
![image](https://user-images.githubusercontent.com/45731/62006058-cd35d980-b14c-11e9-822f-5151c4daa4a3.png)

Pod file is : 
Autolinking cannot find the pod-spec so i have to set the custom path.
```   pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios/RCTRestart.podspec' ```

**Comment by HasanAlyazidi** [comment]
Same issue on iOS and working on Android flawlessly

**Comment by avishayil** [comment]
I haven't had the time yet to test the compatibility with RN 0.60. There is an issue for that, Hope to find the time soon.

**Comment by ynstl** [comment]
I got the same error. I applied the method here for the solution. and problem solved
[https://github.com/avishayil/react-native-restart#credits](url)

**Comment by Diwei-Chen** [comment]
Setting the custom path throwing this warning when doing `pod install`:
`[!] Unable to read the license file 'LICENSE' for the spec 'RCTRestart (0.0.12)'`

**Comment by jasonalmaturner** [comment]
@Diwei-Chen Looks like that's fixed with this change, but hasn't been published as a release yet: https://github.com/avishayil/react-native-restart/commit/55e2f85f094f56a3dedbe06b2610dd1b6aa34f63

**Comment by Diwei-Chen** [comment]
@jasonalmaturner Thanks for the information.

**Comment by avishayil** [comment]
I will test this change soon and hope it will be solved with the discussed change.

**Comment by AylwSt01** [comment]
im also getting this error but on react-native 0.59.8

**Comment by wodCZ** [comment]
Current master branch seems to work fine on iOS with (current) react native 0.60.4.

**Comment by janpe** [comment]
@avishayil are you planning on making a release for this fix?

**Comment by avishayil** [comment]
Released 0.0.13.
