### ISSUE TITLE
Not work on RN 0.60.4 IOS.

### ISSUE THREAD

**Issue by KonstantinMuliarchuk** [avishayil/react-native-restart#99]
Works fine on android, but not restart app on iOS .

**Comment by avishayil** [comment]
Still haven't been tested for RN 0.60.

**Comment by Mahfa** [comment]
this commit fixes this issue https://github.com/avishayil/react-native-restart/commit/55e2f85f094f56a3dedbe06b2610dd1b6aa34f63

**Comment by andreslargo** [comment]
Same here!

**Comment by avishayil** [comment]
Release 0.0.13.
